---
  # Ansible and Ansible Tower, Bind DNS, and NFS Storage
  - name: toolbox
    ip:   192.168.1.100
    memory: 2048
    
    provisions:
      - type: file
        src: dns
        dest: /vagrant/dns
      
      - type: shell
        script: shell/setup_dns.sh
        args:
        
      - type: file
        src: ansible
        dest: /vagrant/ansible
        
      - type: shell
        script: shell/setup_ansible.sh
        args:

  # Cluster Master
  - name: master
    ip:   192.168.1.101
    memory: 3072
    
    disks:
      - location: disks/master-docker
        size: 15
        sata: no
        
   # Docker Register, and HA Proxy
  - name: infra
    ip:   192.168.1.110
    memory: 2048
    
    disks:
      - location: disks/infra-docker        
        size: 20
        sata: no      

   # Worker node1
  - name: node1
    ip:   192.168.1.111
    memory: 2048
    
    disks:
      - location: disks/node1-docker   
        size: 20
        sata: no
      - location: disks/node1-gluster  
        size: 50
        sata: yes
        port: 1
        device: 0 

   # Worker node2
  - name: node2
    ip:   192.168.1.112
    memory: 2048
    
    disks:
      - location: disks/node2-docker
        size: 20
      - location: disks/node2-gluster
        size: 50
        sata: yes
        port: 1
        device: 0

   # Worker node3
  - name: node3
    ip:   192.168.1.113
    memory: 2048

    disks:
      - location: disks/node3-docker
        size: 20
      - location: disks/node3-gluster
        size: 50
        sata: yes
        port: 1
        device: 0
