---

- name: Copy public key to authorized_key
  #hosts: all
  #sudo: True
  
  tasks:
    - name: Set up authorized_key for root user
      authorized_key:
        key="{{lookup('file', '../keys/id_rsa.pub')}}"
        user=root
        
    - name: Set up authorized_key for vagrant user
      authorized_key:
        key="{{lookup('file', '../keys/id_rsa.pub')}}"
        user=vagrant
        