---

- name: Yum update and install basic tools
  #hosts: all
  #sudo: True
  
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        
    - name: install the latest version of bind-utils
      yum:
        name: bind-utils
        state: latest
        